### PR TITLE
Support for remote Aria2.

### PR DESCRIPTION
**Pull request by tatodorov**
Added support for remote Aria2.
This is to address Issue #41.
The input fields "ARIA2 Address" and "ARIA2 Port" can be found under
Settings->Administration->Additional Settings.
If any of the fields is blank, its default value will be used.
"ARIA2 Address" defaults to http://127.0.0.1
"ARIA2 Port" defaults to 6800.

### CODE REVIEW

**Comment by e-alfred** [comment]
Awesome, thanks for your help! Do you think you could add the RPC secret (https://aria2.github.io/manual/en/html/aria2c.html?highlight=secret#rpc-auth) for additional security?

**Comment by tatodorov** [comment]
> 
> 
> Awesome, thanks for your help! Do you think you could add the RPC secret (https://aria2.github.io/manual/en/html/aria2c.html?highlight=secret#rpc-auth) for additional security?

Hi, I'll be glad to.
Do you mind if I make it via separate PR and you merge this one?

I have no prior experience with PHP and have no idea how much time I will need.
In order to create this PR I just analyzed the existing code and then figured out how to implement the functionality.

**Comment by tatodorov** [comment]
> 
> 
> Awesome, thanks for your help! Do you think you could add the RPC secret (https://aria2.github.io/manual/en/html/aria2c.html?highlight=secret#rpc-auth) for additional security?

Done!
RPC authorization secret token is already supported.

**Comment by e-alfred** [comment]
Awesome work! I will test it and then merge it as soon as possible for a new release.

**Comment by e-alfred** [comment]
I will merge this, but as a TODO an error message like "Authorization failed, token invalid?" should be added as a response to the user of the token isn't correct.

**Pull request merged**
