### PR TITLE
Patch to Nibbels 1.5.2

### PR DESCRIPTION
**Pull request by Nibbels**
I downloaded your branch, changed it manually according to my changes and according to the changes of Loki3000/Djazz.
Then uploaded it as a new branch on my fork.

This new fork is now the main fork "e-alfred-master".
That is 
#Nibbels | Moving to e-alfred/ocdownloader for further development …| ac33228
#Nibbels | dont need that file for this new branch …| e6c9171
Whatever history github keeps, it is because of my "Upload Files"-Action to the original master branch. 

I dont relly know about those license-changes. I just left those out in the process.
If I have to undo all the fixes Loki3000 and DjassLab did to the branch tell me! Couldnt refork yours, because I didnt want to delete DjassLabs master. Tell me if I have to!

### CODE REVIEW

**Comment by e-alfred** [comment]
Thanks for you effort. I will take a look into it and then merge it.

**Comment by e-alfred** [comment]
I took a look into it and saw that you added a few of the commits back from after the license change to CC-BY-SA. Could you modify your PR to only contain your changes in a single commit? That way I can do a clean merge without facing the license problem again, because the current one includes @DjazzLab 's and @Loki3000 's changes from after the licence change.

**Comment by Nibbels** [comment]
The license should have been cleaned out now :)

**Comment by Nibbels** [comment]
I tested the HTTP-download with nextcloud 12.0.2
It works. But I was not able to enable the app because it was incompatible with "max version 11". I changed that to 12 now.

I did not test all the other download functions.

**Comment by e-alfred** [comment]
I incorporated your changes manually to preserve a clean commit history. Thanks for your work, I pushed it already mentioning you in the Readme file for helping out. Next step would be to push it to the Nextcloud store.

**Comment by Nibbels** [comment]
I guess it is now the time to clean up my repositories and to refork your branch :)

**Pull request closed without merging**
