### PR TITLE
Add tooltip with full filename to the interface

### PR DESCRIPTION
**Pull request by Loki3000**

### CODE REVIEW

**Comment by Nibbels** [comment]
Nice, thank you very much and hello :)

**Comment by Nibbels** [comment]
screenshot_1

Am I right? And if the filename would be extensive long it would shorten in list and fully expanded in title, correct?

**Comment by Loki3000** [comment]
Yes. You right: display name is only 40 chars, but name in tooltip has no limits.

**Comment by Loki3000** [comment]
I formatted code with PSR2. Some long strings has to be rewritten. There are lots of nested conditions: hard to debug and almost impossible to read. It's to be good to pay attention to such places.

**Comment by Nibbels** [comment]
When I add

**Comment by Loki3000** [comment]
shot
I've download it without any problems.

**Comment by Nibbels** [comment]
Are you using ARIA2 or CURL?

Curl worked on me when I just switched and tested it with curl.
screenshot_2
screenshot_3

and quite nice:
screenshot_4

I will pull your other commits to my branch now.

**Comment by Nibbels** [comment]
ok ... on my system rightnow not even http://downfight.de/ThisIsSomeReallyTest.stl works.

**Comment by Nibbels** [comment]
... and this might also be some problem with my redis server or whatever.
Can anyone test this with Aria2?
screenshot_5

**Comment by Nibbels** [comment]
oh yeah.... disabled redis as memcache and now it works! Sorry for confusing everyone.
screenshot_6

**Comment by Nibbels** [comment]
ok..... one other thing.
when I pull your patch with the renaming I have no problems at all.
But when I pull the rest of your commits I think that torrents have some problem. Can you please retest this with your newest branch @Loki3000 ?

When some torrent is in queue all is fine but when I add one with the newest version of yours it sais failed and vanishes into thin air.

screenshot_8
screenshot_9
screenshot_10

Am I right here or should I get some rest off todays heat? ^^

**Comment by Nibbels** [comment]
Moved all files back to ocdownloader-324f01b2961aa07f2dad6f3012f04491ef61341d:
screenshot_10

**Comment by Loki3000** [comment]
I added and download torrent without any errors. Could you provide more information how to get error?
torrent

**Comment by Nibbels** [comment]
Nice... I just saw the mail.
So I can give you a feedback in some minutes...

**Comment by Nibbels** [comment]
simple check: I compared the functions names:
https://aria2.github.io/manual/en/html/aria2c.html#aria2.addTorrent
your version with lowercase start of addTorrent could even be more compatible than `AddTorrent`

**Comment by Loki3000** [comment]
I know:)
I just missed it when replace all function calls.

**Comment by Nibbels** [comment]
screenshot_3
screenshot_4
Torrents seem to be fixed!

About your last commit: you fixed the .min.js so I guess you did already do this to tne normal .js without compression? (I dont have the time to check it rightnow.)

**Comment by Loki3000** [comment]
Yes. Uncompressed file was ok from yesterday commit.

**Comment by e-alfred** [comment]
Thanks for helping us out again @Loki3000! I will test it (but @Nibbels did that already, great work!) so I will try to merge it as soon as possible.

**Comment by Nibbels** [comment]
I did not test CURL and not FTP and not Youtube for now... 
Only ARIA2 with long Filenames and Bittorrent. I am gonna test more when I have some sparetime left for this. If you test some of those conditions comment them here.
:)

**Comment by e-alfred** [comment]
I tired it out on my test setup but if I add a download (regardles of type or downloader), the filename is shown as "undefined" an the tooltip doesn't work either. I will have to take a closer look into it.

**Comment by e-alfred** [comment]
I tested it out and it works pretty well with all download types. Thanks for your work @Loki3000!

**Comment by e-alfred** [comment]
I had to restart Apache, then the problem with showing "undefined" went away and the real filenames were shown.

**Pull request merged**
