### PR TITLE
Some changes in design.

### PR DESCRIPTION
**Pull request by Nibbels**
On my trip through the code I ended up doing some skin-deep changes.
I like them but not everyone has to ^^.

This pull request is open for discussion.
screenshot_11
screenshot_10

First: I removed this huge banner with ads for the plugin itself ^^
"Manage Your Downloads Anywhere!"
"nough dealing with tricky downloads syntax. Manage your downloads via the web easily with CURL/ARIA"

Second: I split the Button for switching protocol type in "Add Downlods" to 4 Buttons. This is much cleaner I think. Saves 1 click each change.

Third: This "Loading..." which was rythmic popping up vor some millisecs have been moved to the bottom of the downloads lists. I somehow annoyed me at the top.

Four: I unlocked all pages for use with CURL. I wasnt able to figure out why the developers did remove those for CURL. Some would discuss if those pages are nice at all - but blocking them for CURL didnt make much sense for me.

What do you think?

### CODE REVIEW

**Comment by Nibbels** [comment]
well ... I wanted to remove this line badly. But I wasnt able to. 
screenshot_12
Does anyone knows how this is set? I had no luck and use some freetime now ;)

**Comment by e-alfred** [comment]
1. I think these phrases are unnecessary indeed. Better to put them in the description of the app in the Readme and the store at some point than cluttering the interface.

2. It makes selection easier indeed, how well does it work on mobile devices (if anybody uses it with one anyway)?

3. I only noticed it before the list was loaded, so it was the only thing in the list.

4. As long as they work it shouldn't be a problem. Listing downloads with a certain stage would be quite usefui for Curl too.

**Comment by Nibbels** [comment]
wp_ss_20170827_0002
wp_ss_20170827_0001
wp_ss_20170827_0003

Using mobiles: Good point! I tested it and it looks nice.

About Downloads in certain stages: I have quite a lot of troubles testing, because my server is Gbit connected. Whatever I download it is finished quite fast.

**Comment by e-alfred** [comment]
Looks good, I appreciate it.

Regarding the Curl problems, a status file is created for every download in the /tmp directory. Here is more on that: https://github.com/e-alfred/ocdownloader/issues/4#issuecomment-325215213

I noticed that both Curl and Youtube-dl downloads don't update the Nextcloud filecache. The files don't show up in Nextcloud even though the files are stored on the filesystem. This problem is fixed with your patch for Aria2 already.

**Comment by Nibbels** [comment]
To update the filecache we have this function now. The question is when we let the function auto-work.
Because I am still scratching on the surface of this apps functionality and digging my head in I did not care for this "automatic"  feature. But of course whenever a download goes to complete the folder should be automatically parsed!
But as I saw sometimes FTP-Downloads dont go to complete somehow. This is another thing that has to be fixed ^^.

**Pull request merged**
