### PR TITLE
support for nextcloud 24

### LINKED ISSUE #245: Add NC24 compatibility
Please, add NC24 compatibility

### LINKED ISSUE #248: [index] Error: Exception: OC\Files\Utils\Scanner::__construct()
I installed all requierements, but when I try to open ocdownloader i get the blue nextcloud error side and this logs:

```
[index] Error: Exception: OC\Files\Utils\Scanner::__construct(): Argument #4 ($logger) must be of type Psr\Log\LoggerInterface, OC\Log given, called in /var/www/html/custom_apps/ocdownloader/controller/index.php on line 249 in file '/var/www/html/lib/private/Files/Utils/Scanner.php' line 95 at <<closure>>

0. /var/www/html/lib/private/AppFramework/App.php line 172
   OC\AppFramework\Http\Dispatcher->dispatch(OCA\ocDownloader\Controller\Index {}, "Add")
1. /var/www/html/lib/private/Route/Router.php line 298
   OC\AppFramework\App::main("IndexController", "Add", OC\AppFramework\ ... {}, ["ocdownloader.Index.Add"])
2. /var/www/html/lib/base.php line 1030
   OC\Route\Router->match("/apps/ocdownloader/add")
3. /var/www/html/index.php line 36
   OC::handleRequest()

GET /apps/ocdownloader/add
from xxx by xxx at 2022-09-14T23:02:26+00:00


{"reqId":"wkIhkhSRtnmfS7pTm37R","level":3,"time":"2022-09-14T23:02:26+00:00","remoteAddr":"xxx","user":"xxx","app":"index","method":"GET","url":"/apps/ocdownloader/add","message":"OC\\Files\\Utils\\Scanner::__construct(): Argument #4 ($logger) must be of type Psr\\Log\\LoggerInterface, OC\\Log given, called in /var/www/html/custom_apps/ocdownloader/controller/index.php on line 249 in file '/var/www/html/lib/private/Files/Utils/Scanner.php' line 95","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:104.0) Gecko/20100101 Firefox/104.0","version":"24.0.5.1","exception":{"Exception":"Exception","Message":"OC\\Files\\Utils\\Scanner::__construct(): Argument #4 ($logger) must be of type Psr\\Log\\LoggerInterface, OC\\Log given, called in /var/www/html/custom_apps/ocdownloader/controller/index.php on line 249 in file '/var/www/html/lib/private/Files/Utils/Scanner.php' line 95","Code":0,"Trace":[{"file":"/var/www/html/lib/private/AppFramework/App.php","line":172,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\ocDownloader\\Controller\\Index"},"Add"]},{"file":"/var/www/html/lib/private/Route/Router.php","line":298,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["IndexController","Add",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},["ocdownloader.Index.Add"]]},{"file":"/var/www/html/lib/base.php","line":1030,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/apps/ocdownloader/add"]},{"file":"/var/www/html/index.php","line":36,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","Line":165,"Previous":{"Exception":"TypeError","Message":"OC\\Files\\Utils\\Scanner::__construct(): Argument #4 ($logger) must be of type Psr\\Log\\LoggerInterface, OC\\Log given, called in /var/www/html/custom_apps/ocdownloader/controller/index.php on line 249","Code":0,"Trace":[{"file":"/var/www/html/custom_apps/ocdownloader/controller/index.php","line":249,"function":"__construct","class":"OC\\Files\\Utils\\Scanner","type":"->","args":["xxx",{"__class__":"OC\\DB\\ConnectionAdapter"},{"__class__":"OC\\EventDispatcher\\EventDispatcher"},{"__class__":"OC\\Log"}]},{"file":"/var/www/html/custom_apps/ocdownloader/controller/index.php","line":91,"function":"syncDownloadsFolder","class":"OCA\\ocDownloader\\Controller\\Index","type":"->","args":[]},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":225,"function":"add","class":"OCA\\ocDownloader\\Controller\\Index","type":"->","args":[]},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":133,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\ocDownloader\\Controller\\Index"},"Add"]},{"file":"/var/www/html/lib/private/AppFramework/App.php","line":172,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\ocDownloader\\Controller\\Index"},"Add"]},{"file":"/var/www/html/lib/private/Route/Router.php","line":298,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["IndexController","Add",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},["ocdownloader.Index.Add"]]},{"file":"/var/www/html/lib/base.php","line":1030,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/apps/ocdownloader/add"]},{"file":"/var/www/html/index.php","line":36,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/var/www/html/lib/private/Files/Utils/Scanner.php","Line":95},"CustomMessage":"--"},"id":"63225d8d15223"}

```

### PR DESCRIPTION
**Pull request by JasonPoon-cn**
/appinfo/app.php is deprecated, use \OCP\AppFramework\Bootstrap\IBootstrap on the application class instead.

closes #245

fixes #248

### CODE REVIEW

**Comment by ayanamidev** [comment]
@JasonPoon-cn Seems like this PR would break support for Nextcloud older than 24, could you revive the support for older versions as well?

**Comment by ayanamidev** [comment]
And, nextcloud 24 have too many bugs so I wouldn't recommend using it, 23 is stable and robust enough

**Comment by JasonPoon-cn** [comment]
> And, nextcloud 24 have too many bugs so I wouldn't recommend using it, 23 is stable and robust enough

I tried do it，but  it‘s break, i'm an amateur, It's difficult for me.

**Comment by JasonPoon-cn** [comment]
@ayanamidev I tried do it，but it‘s break, i'm an amateur, It's difficult for me.

**Comment by bekon16** [comment]
I have checked this PR on version 24.0.1 and it works like a charm.

**Review by weeman1337 — APPROVED** [review]

**Comment by weeman1337** [comment]
Tested on NC24, works.

Thanks @JasonPoon-cn for your contribution.

@e-alfred can you merge this and publish a release?

**Review by blackcrack — APPROVED** [review]

**Comment by weeman1337** [comment]
@e-alfred did you had a chance to look at this PR?

**Comment by blackcrack** [comment]
last activity Dec. 27 2021 :\  hmmm... covit ?

**Comment by 0rb1ta** [comment]
Good afternoon, you did not make this fix in release 1.8.1, the current version is not compatible with nс 24

**Comment by 0rb1ta** [comment]
> Hello. And fix by [nlublovary](https://github.com/nlublovary) is not working in 24.0.4. At least for me.

For me - working, 
249 line - $scanner = new \OC\Files\Utils\Scanner($user, \OC::$server->getDatabaseConnection(), \OC::$server->query(IEventDispatcher::class), \OC::$server->get(LoggerInterface::class));
24 line - use Psr\Log\LoggerInterface;

**Comment by BUG-reporter** [comment]
> > Hello. And fix by [nlublovary](https://github.com/nlublovary) is not working in 24.0.4. At least for me.
> 
> For me - working, 249 line - $scanner = new \OC\Files\Utils\Scanner($user, \OC::$server->getDatabaseConnection(), \OC::$server->query(IEventDispatcher::class), \OC::$server->get(LoggerInterface::class)); 24 line - use Psr\Log\LoggerInterface;

Oh, I forgot about line 24. It is working for me again in 24.0.5.

**Comment by e-alfred** [comment]
Thank you for your PR, I merged it and make a new release as soon as possible.

**Pull request merged**
